// <auto-generated />
using Kias_Kar_Kompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kias_Kar_Kompany.Migrations
{
    [DbContext(typeof(Kias_Kar_KompanyContext))]
    [Migration("20260414104116_commit")]
    partial class commit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManId"));

                    b.Property<string>("Manufacturer_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManId");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Owner", b =>
                {
                    b.Property<int>("ownerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ownerId"));

                    b.Property<string>("ownerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ownerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ownerNumber")
                        .HasColumnType("int");

                    b.HasKey("ownerId");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int?>("ManId")
                        .HasColumnType("int");

                    b.Property<int?>("ManufacturerManId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehiclePrice")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ownerId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("ManufacturerManId");

                    b.HasIndex("ownerId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Vehicle", b =>
                {
                    b.HasOne("Kias_Kar_Kompany.Models.Manufacturer", "Manufacturer")
                        .WithMany("Vehicles")
                        .HasForeignKey("ManufacturerManId");

                    b.HasOne("Kias_Kar_Kompany.Models.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("ownerId");

                    b.Navigation("Manufacturer");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Manufacturer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Kias_Kar_Kompany.Models.Owner", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
